name: gitee

on: 
  - push
  - delete

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: wangchucheng/git-repo-sync@v0.1.0
      with:
        target-url: https://gitee.com/cskefu/cskefu-docs.git
        target-username: ${{ secrets.USERNAME }}
        target-token: ${{ secrets.ACCESS_TOKEN }}